language: node_js
#sudo: true
node_js:
- 4.2.3
env:
  global:
  - CF_APP=federalist
  - CF_API=https://api.cloud.gov
  - CF_USERNAME=deploy-federalist
  - CF_ORGANIZATION=federalist
  - CF_SPACE=prod
  - secure: dQnuUVyWtfYtjXuMXZJ48IN14M+FnbJ/euMOrBolxBnqKbQkLbnKY+BsGsgM1Lj9r611gczWIkt1Lv487gc2Z1LSWnTMrwgFLG4C7B+n7nRkhZGo8aisp+KjzeJljVkj7XoMNJ23qYkkAZ40/TpCj8C2CVGDvf2H9L0O0NlEkZCTmSWyvBSJ/+FHZVFICM8sm4qrGjDKTlPEaPS+ZHBHp3Ow6irpgCYfFPGyODEIkGfAzAu7t3Ta4cOaC7ha1hr+ayj9W6ImGvFvK1hFWQkpDiJanK+42keCk8KPJAwmP6a0r4BJ6UtzmNlN7N4+BL8WhvS3QrgWiEWjEVSli3Y3IUUS66hPOo0YrzbPK5TBscgh9HyWpPooKz8se5J8ehvhCR/vOzjJpg1AVeegCJczWe4t/XWNZKHtqu7z6e0Ft7DuDAUvY1BSObNSPPCP6Omx69nfeRENj5QEZNM7hFMxBQxBHmUdFroogN2jAXx4i8sTLfMUr0sDFyslX8FRrQtCUIKSvHzBwLb57riRnv3YfI9MNG2hOqN0aeQFQ2v65+Q02f6Ms6Jrj5YQV6B8dJ9RkwCXoDKN+FOtjepYaQCZbBWqnJJlULYVp/fVkHaU4COxUt3t86/w2ymYuLBvgeLEpYC8JIoM6T0V8dfE6kH3OvvYNEW4L2+w8rZU25St1Xs=
  - CXX=g++-4.8
  - FEDERALIST_TEST_USER=federalist-test
  - FEDERALIST_TEST_ORG=17072414
  # FEDERALIST_TEST_PASSWORD
  - secure: "wBLW/4uaD7GzMPqEgqJAUvMRi1BHJrPQLhRvfMY8FLdpUD1D8zsw70WajPVwWJ7ts0dK1E8TC1hSp63yawgmZ3UFwDNOWRBlr1fxelh2dInYG4VDT82PESYbgHq4HY37ACS6aqZ8ntYkXjjqi4vstRpU+KtpmXf2MSZhkPwyD4ULeA/g+6fSVnDgZ4eXjYWQUYfLKe4lTlD2qSedhcFwRJdk0RJSo29i3ouEryJ/MD5h2bfaUqXcBBXmxvbqdX27Uecr5wBh/w0mEuzIIApFwJcYt3VyaPQuvGkFT7MbvOtv4PE8aQZYjZ72ykjaM5LhwV23RQKJCAyOYyph6wwE2iafLcSMLPJ3ohyQe/s+TUCxKdEvPaNyVZviANJhNFAN+FepsT5E1hsZiYocauE3slV2uoTdEfYsozaP9gFs4y51QcGYrrz5AP6LOq3YlJP9ikGqP8jwzAdXqQbA/tm1djjGUc8HWm5nSl4OCfM3Z9asVOfN3hrHk7IzYi9x8FfmNV3kIwoyXQaV3pXT6ebeOSY3qfEOxvdYgSw7Uu1B1O27/n/ZSRvk2WpqMj8c+zhUv2OZpQJYJbX3AoREf5KsAVRA+sevRhN+Fb5L5vgfCQyGYn+LKOekm9njZEsb1JuisUcdiXI68AXgHCSveba1o77yem8PP6PpSvJ+oXCXcXk="
  - GITHUB_CLIENT_ID=e1546b0daa6206853e16
  # GITHUB_TOKEN
  - secure: KcpUNUJkps0vsFeMuYizvZlkrlBeUHkMs+32m3IHpvVtVzN7jVnera8ZCtyR9tK1IHmY9hpwer4dGQaclikECzwe0gdc/JTUCL9BAbN/FV8lXZQXaNmuT2np4FFRD4WoKs2PA/qGhKfsq2GkXEmyrFiwH2xsD4XFzjLYqcAbjK1tNVxldTe/QDMB7Q1gh/YNTqexWUPfLTsr/iZJbDJab2iiTNw7NssirzGeYZEkabsUN2BOzY2tZjyx8Yp4ce4n+IL5nKho05cMAZ7AOhPbHzy2MKUTJos2LxpcC2cYY/uSZfwD3MPy2MZKlpf+ncCGHW7cYEFOnxmXhSHyG8ocJYyF2uhON66EoiqiKcAzOGHDAJGHAuevJgF1227IVzurEoPTkkQgL+FZFXb+HP0YHRO9Xq7S2wdPUpH8KpNH1tfWSaXb6f08aTB8F6So4EcSj6Bf7Rm8S5vKlHF6B7PGDKFgBFcMmUftWCNsrvzQfwqEpOEJLsb9q9dNkg7QS0D6LsCmMLtPC9IUMTfb/iy3ati0fBKFZOA6F4MueqXniWpmuJJu4ZHArWd342lD/tzvmJu39ddiwbhTXbqYyqxvsfMOf9ZrZK6mEWB7WlBAuoc+689OHuuEVkmTBneu+YO8u40Lx2FX2FtbFx0L2fyja/W4tN0V0uBsr5hd2GeQhuk=
  - secure: vdCYsorWG4U2QNvGO3KTGHRRja65casVSTwyMWr5h6rpdnJ9ima40eQkX3tdkR2QS5PcOiryj92w18rHJoTo9xUzg6e2O2gS23y2BQhgJcmQq4638ISiDLFE3BYU1aUasvgX1Vm4x+zyitSP+9juGDdRwnmcAIFrmXItDoiljZFQpsGuy2Loc9H4Mj7N+89jJUqQy9DvJ26p2zBlgduQjvo/BAGoRkTP5JZMn0c//KWdqhuGnxCA2g/MmEnKaQ5ltziM7byYvIaVMGPbjM+KOpYOnicZsNte8DA5kmsk1/TVKvi5EZEcz7xq4j2p+J/GKHGflHiVbo4fjIo+sJqCATo29Rx5WHMaYeTRDyAV5dhzv+6EXHSo2yH4D2Ywpsprpp/xo4RoxJcJpPSi0mTUsphhvHlFnRdwbWCh8ah+JbtsNDNiGFLaB6aKntuDPE2mRSXCchpynAkLkwlxG7rcJtFYNdzT6DOgKTioEZc+6syNKs5AWFuE+80m2+pynkrMzSz8gY9WbrIq/JKJcbCPlISflYZ1TzOrTN/9c+dm64WEr59YZuR6nH1IDeFOtI3yJmbJSJ64MJKEZ9Q94V18MmuRKsoWZazGKmT8ACTlcrjPS9UoCnNgBhVIJQEDrpdf09zMcq+/LWPXU2g9rT76igBG4XBWEBNchfLRsn2md8E= # SAUCE_ACCESS_KEY
  - SAUCE_USERNAME=aborden_18f
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  sauce_connect: true
deploy:
  provider: script
  script: scripts/deploy-travis.sh
  on:
    branch: master
notifications:
  slack:
    on_success: never
    on_failure: always
    on_start: never
    on_pull_requests: false
    secure: Eqyu9MVlzDtdFgc/Wv89Br2yuvuh0HRoLMjbpS1KDgZ4si0/aBggV67MaVNiRpEH5Q3Sr01K3M0UfJBU2nJzVlmqkF1zEMVqz0Kox8Qn4EaUSog2DS0X8quU1HAvaqIu+HtwXchcBEhiK1agd79pN3djvr2kGGPdZLqkz4XT+zsRcPgiUcp1oyzCpmqKXv16+7F5RX+pA+CgsawRzOY39qe44HIixxRzJeOxaB+16ccaauqTqxIuBUqlNn1wmlxbYYzTeniF7lJULNMkHcz16pRs6w4vssjUJRsdoKvnyRY33sKKRaWPitzEjAjQNiZeLEym3DG1569xPXjKcvp42Vax5sA20pF92a8E0BQckADSk8wcq3G8Ak58LEg1CvAxp6vQvrcTB1k+/QSg2Y1mzHoEH9d2gebgVZIgn6iqSgHjYxNjCREUhE/SC9pOuaGuJuMhaeCHW/7Ucr0IPwAvzpvKWa1qzDgHLGVlFEI8rTstSnFif0oR7bM7pqdZLEQkpfrE/rV5II19O1c4/hN0JHE6bLNHrULmmYTz/cWqUkuR69OwnifQZGdU06tMrE8u5sdKWbjKMjlRhGHhhsQCW7VQ0NJp7GLJwz9mL8Aq0TH9J4pItGDW++3PfaJpaSHv8UhCCg0GRWEhve2P9JMHldLuij0qR73KjrV2HyER9LA=
